window.FE_QUESTIONS = [
  {id:1,section:"A",category:"ネットワーク",importance:"S",question:"LAN内の端末が、ホスト名ではなくIPアドレスから対応するMACアドレスを調べるときに利用するプロトコルはどれか。",options:["ARP","DNS","DHCP","NTP"]},
  {id:2,section:"A",category:"ネットワーク",importance:"S",question:"ドメイン名 www.example.jp に対応するIPアドレスを問い合わせるために利用する仕組みはどれか。",options:["ARP","DNS","SMTP","SNMP"]},
  {id:3,section:"A",category:"ネットワーク",importance:"S",question:"WebブラウザとWebサーバ間のHTTPS通信で、通信内容の暗号化やサーバ認証に利用されるものはどれか。",options:["ICMP","TLS","FTP","ARP"]},
  {id:4,section:"A",category:"OS",importance:"S",question:"仮想記憶で、プログラムが参照しようとしたページが主記憶に存在しないときに発生するものはどれか。",options:["ページフォールト","デッドロック","スラッシングだけ","割込み禁止"]},
  {id:5,section:"A",category:"OS",importance:"S",question:"仮想記憶方式で、必要になったページをその都度補助記憶装置から主記憶へ読み込む方式はどれか。",options:["パイプライン処理","デマンドページング","スプーリング","キャッシュライトスルー"]},
  {id:6,section:"A",category:"セキュリティ",importance:"S",question:"利用者のパスワードをハッシュ化して保存するとき、同じパスワードでも同一のハッシュ値になりにくくするために付加するランダムな値はどれか。",options:["ソルト","チャレンジコード","セッションID","秘密鍵"]},
  {id:7,section:"A",category:"セキュリティ",importance:"S",question:"Webページに入力された文字列を適切にエスケープせず、そのままHTMLへ出力することで発生しやすい攻撃はどれか。",options:["SQLインジェクション","クロスサイトスクリプティング","ブルートフォース攻撃","DoS攻撃"]},
  {id:8,section:"A",category:"セキュリティ",importance:"S",question:"同一アカウントへの連続したログイン失敗が一定回数を超えたとき、一時的にアカウントをロックする対策が特に有効な攻撃はどれか。",options:["クロスサイトスクリプティング","ブルートフォース攻撃","SQLインジェクション","DNSキャッシュポイズニング"]},
  {id:9,section:"A",category:"プロジェクトマネジメント",importance:"S",question:"アローダイアグラムで、遅延するとプロジェクト全体の完了時期が遅れる経路はどれか。",options:["マイルストーン","クリティカルパス","WBS","スプリント"]},
  {id:10,section:"A",category:"プロジェクトマネジメント",importance:"S",question:"プロジェクトで実施すべき作業を階層的に分解し、管理可能な単位まで細分化したものはどれか。",options:["WBS","ER図","DFD","PERTだけ"]},
  {id:11,section:"A",category:"システム構成",importance:"S",question:"稼働率0.8の装置を2台並列に接続し、どちらか一方が稼働していれば利用できる。故障が独立しているとき、システム全体の稼働率はいくつか。",options:["0.64","0.80","0.96","1.60"]},
  {id:12,section:"A",category:"システム構成",importance:"A",question:"稼働率0.9の装置を2台直列に接続し、両方が稼働しているときだけシステムが利用できる。故障が独立しているとき、システム全体の稼働率はいくつか。",options:["0.81","0.90","0.99","1.80"]},
  {id:13,section:"B",category:"論理演算",importance:"S",question:"ド・モルガンの法則により、NOT(A OR B) と常に等しい論理式はどれか。",options:["(NOT A) OR (NOT B)","(NOT A) AND (NOT B)","A AND B","A OR (NOT B)"]},
  {id:14,section:"B",category:"再帰",importance:"S",question:"次の関数fを実行したとき、f(4)の戻り値はいくつか。",code:"function f(n)\n    if n = 0 then\n        return 0\n    else\n        return n + f(n - 1)\n    endif\nendfunction",options:["6","10","16","24"]},
  {id:15,section:"B",category:"再帰",importance:"S",question:"次の関数gを実行したとき、g(6)の戻り値はいくつか。",code:"function g(n)\n    if n <= 1 then\n        return n\n    else\n        return g(n - 1) + g(n - 2)\n    endif\nendfunction",options:["5","8","13","21"]},
  {id:16,section:"B",category:"キュー・スタック",importance:"A",question:"空のスタックに PUSH(A), PUSH(B), PUSH(C), POP(), PUSH(D), POP() を実行した。次にPOP()すると取り出される値はどれか。",options:["A","B","C","D"]},
  {id:17,section:"B",category:"探索",importance:"S",question:"昇順配列 [3, 8, 12, 17, 25, 31, 44] に二分探索で8を探す。最初に17と比較した後、次に比較する値はどれか。",options:["3","8","12","25"]},
  {id:18,section:"B",category:"配列・ループ",importance:"S",question:"次の処理を実行した後のcountの値はいくつか。配列の添字は1から始まる。",code:"A ← [2, 7, 4, 9, 6]\ncount ← 0\nfor i ← 1 to 5\n    if A[i] MOD 2 = 0 then\n        count ← count + 1\n    endif\nendfor",options:["2","3","4","5"]},
  {id:19,section:"B",category:"ソート",importance:"S",question:"配列 [5, 1, 4, 2] に対して、左から隣接要素を比較し、左が大きければ交換する操作を末尾まで1回行った。処理直後の配列はどれか。",options:["[1, 4, 2, 5]","[1, 5, 4, 2]","[5, 1, 2, 4]","[1, 2, 4, 5]"]},
  {id:20,section:"B",category:"アルゴリズム",importance:"S",question:"次の処理を実行したとき、xの値はいくつか。",code:"x ← 1\nfor i ← 1 to 3\n    x ← x * 2 + 1\nendfor",options:["7","9","15","17"]}
];
