window.FE_QUESTIONS = [
  {id:1,section:"A",category:"セキュリティ",importance:"S",question:"Webアプリケーションで、利用者の入力内容をHTMLとしてそのまま出力した場合に発生する可能性が高い攻撃はどれか。",options:["クロスサイトスクリプティング","DNSキャッシュポイズニング","ARPスプーフィング","ブルートフォース攻撃"]},
  {id:2,section:"A",category:"ネットワーク",importance:"S",question:"TCP/IPネットワークで、IPアドレスから対応するMACアドレスを求めるために用いるプロトコルはどれか。",options:["DNS","DHCP","ARP","SMTP"]},
  {id:3,section:"A",category:"OS",importance:"S",question:"仮想記憶方式において、実行に必要になったページを補助記憶装置から主記憶へ読み込む方式はどれか。",options:["スプーリング","デマンドページング","パイプライン処理","ラウンドロビン"]},
  {id:4,section:"A",category:"プロジェクトマネジメント",importance:"S",question:"プロジェクトの作業を階層的に細分化し、管理可能な単位まで分解したものはどれか。",options:["WBS","DFD","ER図","状態遷移図"]},
  {id:5,section:"A",category:"ネットワーク",importance:"S",question:"HTTPSで一般に利用され、HTTP通信を暗号化するためのプロトコルはどれか。",options:["TLS","FTP","SNMP","ICMP"]},
  {id:6,section:"A",category:"セキュリティ",importance:"S",question:"パスワードを保存するとき、同じパスワードでも異なるハッシュ値になりやすくし、レインボーテーブル攻撃への耐性を高めるために追加する値はどれか。",options:["ソルト","セッションID","公開鍵","デジタル署名"]},
  {id:7,section:"A",category:"データベース",importance:"A",question:"トランザクションのACID特性のうち、処理が全て実行されるか、全く実行されないかを保証する性質はどれか。",options:["一貫性 Consistency","原子性 Atomicity","独立性 Isolation","永続性 Durability"]},
  {id:8,section:"A",category:"システム構成",importance:"A",question:"稼働率0.9の装置を2台並列に接続し、どちらか1台が稼働していればシステムが利用できる。両装置の故障が独立しているとき、システムの稼働率はいくつか。",options:["0.81","0.90","0.95","0.99"]},
  {id:9,section:"A",category:"プロジェクトマネジメント",importance:"A",question:"アローダイアグラムにおいて、プロジェクト全体の所要期間を決定し、遅延するとプロジェクト全体が遅れる経路を何というか。",options:["クリティカルパス","マイルストーン","ベースライン","スプリント"]},
  {id:10,section:"A",category:"ストラテジ",importance:"A",question:"企業の内部環境を強み・弱み、外部環境を機会・脅威に分類して分析する手法はどれか。",options:["PPM","SWOT分析","ABC分析","パレート分析"]},
  {id:11,section:"B",category:"ループ",importance:"S",question:"次の処理を実行したとき、sumの値はいくつか。",code:"sum ← 0\nfor i ← 1 to 5\n    if i MOD 2 = 1 then\n        sum ← sum + i\n    endif\nendfor",options:["6","9","10","15"]},
  {id:12,section:"B",category:"配列・ループ",importance:"S",question:"次の処理を実行した後のxの値はいくつか。配列の添字は1から始まる。",code:"A ← [3, 8, 2, 7, 5]\nx ← 0\nfor i ← 1 to 5\n    if A[i] > 5 then\n        x ← x + 1\n    endif\nendfor",options:["1","2","3","4"]},
  {id:13,section:"B",category:"探索",importance:"S",question:"昇順配列 [4, 9, 15, 21, 28, 34, 40, 51] に二分探索で34を探す。中央要素を範囲の小さい側の中央とすると、比較される値の順序として適切なものはどれか。",options:["21 → 34","28 → 34","21 → 40 → 34","28 → 40 → 34"]},
  {id:14,section:"B",category:"キュー",importance:"S",question:"空のキューに ENQUEUE(A), ENQUEUE(B), DEQUEUE(), ENQUEUE(C), ENQUEUE(D), DEQUEUE() を順に実行した。次にDEQUEUE()したとき取り出される値はどれか。",options:["A","B","C","D"]},
  {id:15,section:"B",category:"ビット演算",importance:"S",question:"8ビット値 10110110 と 00001111 のANDをとった結果はどれか。",options:["00000110","00001001","10110000","10111111"]},
  {id:16,section:"B",category:"再帰",importance:"S",question:"次の関数gを実行したとき、g(5)の戻り値はいくつか。",code:"function g(n)\n    if n <= 1 then\n        return n\n    else\n        return g(n - 1) + g(n - 2)\n    endif\nendfunction",options:["3","5","8","13"]},
  {id:17,section:"B",category:"ソート",importance:"S",question:"配列 [4, 3, 2, 1] に対して、左から隣接要素を比較し、左が大きければ交換する操作を末尾まで1回行った。処理直後の配列はどれか。",options:["[1, 4, 3, 2]","[3, 2, 1, 4]","[3, 4, 2, 1]","[1, 2, 3, 4]"]},
  {id:18,section:"B",category:"論理演算",importance:"A",question:"論理式 NOT(A AND B) と常に同じ結果になるものはどれか。",options:["(NOT A) AND (NOT B)","(NOT A) OR (NOT B)","A OR B","A AND (NOT B)"]},
  {id:19,section:"B",category:"セキュリティ",importance:"S",question:"ログイン処理で、5回連続して認証に失敗したアカウントを一定時間ロックする仕組みが主に軽減する攻撃はどれか。",options:["SQLインジェクション","ブルートフォース攻撃","クロスサイトスクリプティング","中間者攻撃"]},
  {id:20,section:"B",category:"アルゴリズム",importance:"S",question:"次の処理を実行したとき、resultの値はいくつか。",code:"result ← 1\nfor i ← 1 to 4\n    result ← result * 2\nendfor",options:["8","16","24","32"]}
];
