window.FE_QUESTIONS = [
{id:1,section:"A",category:"セキュリティ",importance:"S",question:"攻撃者が用意したWebページなどを経由して、ログイン済み利用者の意図しない操作をWebサービスに実行させる攻撃はどれか。",options:["クロスサイトスクリプティング","CSRF","SQLインジェクション","ブルートフォース攻撃"]},
{id:2,section:"A",category:"セキュリティ",importance:"S",question:"正規の利用者から漏えいしたIDとパスワードの組合せを使い、別のサービスへのログインを試みる攻撃はどれか。",options:["パスワードリスト攻撃","辞書攻撃","DoS攻撃","セッションハイジャック"]},
{id:3,section:"A",category:"ネットワーク",importance:"S",question:"IPv4ネットワークで、192.168.10.0/26 のサブネットに割り当てられるIPアドレス総数はいくつか。",options:["32","62","64","126"]},
{id:4,section:"A",category:"ネットワーク",importance:"A",question:"TCPとUDPの説明として適切なものはどれか。",options:["UDPは必ず再送制御を行う","TCPはコネクション型で再送制御などを行う","TCPはIPアドレスを使用しない","UDPは必ずTLSで暗号化される"]},
{id:5,section:"A",category:"データベース",importance:"S",question:"関係データベースの正規化を行う主な目的として、最も適切なものはどれか。",options:["通信速度を向上させる","データの重複や更新時の不整合を抑える","全ての表を一つに統合する","主キーを削除する"]},
{id:6,section:"A",category:"データベース",importance:"A",question:"SQLのSELECT文で、集計後のグループに対して条件を指定するときに使用する句はどれか。",options:["WHERE","ORDER BY","HAVING","FROM"]},
{id:7,section:"A",category:"システム構成",importance:"S",question:"MTBFが900時間、MTTRが100時間のシステムの稼働率はいくつか。",options:["0.10","0.50","0.90","0.99"]},
{id:8,section:"A",category:"ハードウェア",importance:"A",question:"CPUのキャッシュメモリを利用する主な目的はどれか。",options:["主記憶とCPUの速度差を緩和する","補助記憶装置の容量を増やす","ネットワーク通信を暗号化する","仮想記憶を無効化する"]},
{id:9,section:"A",category:"プロジェクトマネジメント",importance:"A",question:"EV=80、PV=100、AC=90 のとき、スケジュール差異SVとコスト差異CVの組合せとして適切なものはどれか。",options:["SV=-20, CV=-10","SV=20, CV=10","SV=-10, CV=-20","SV=10, CV=20"]},
{id:10,section:"A",category:"ストラテジ",importance:"A",question:"市場成長率と相対的市場占有率の2軸で事業を分類する分析手法はどれか。",options:["SWOT分析","PPM","ABC分析","ファイブフォース分析"]},
{id:11,section:"A",category:"ソフトウェア開発",importance:"A",question:"アジャイル開発で、短い期間を区切って計画・開発・評価を繰り返す期間を、スクラムでは一般に何というか。",options:["スプリント","クリティカルパス","マイルストーン","ベースライン"]},
{id:12,section:"A",category:"セキュリティ",importance:"S",question:"デジタル署名によって主に確認できるものの組合せはどれか。",options:["機密性と可用性","改ざんの有無と署名者の確認","通信速度と圧縮率","パスワード強度と稼働率"]},
{id:13,section:"B",category:"スタック",importance:"S",question:"空のスタックに PUSH(2), PUSH(5), POP(), PUSH(7), PUSH(9), POP() を実行した。次にPOP()したとき取り出される値はどれか。",options:["2","5","7","9"]},
{id:14,section:"B",category:"キュー",importance:"S",question:"空のキューに ENQUEUE(A), ENQUEUE(B), ENQUEUE(C), DEQUEUE(), ENQUEUE(D), DEQUEUE() を実行した。次にDEQUEUE()したとき取り出される値はどれか。",options:["A","B","C","D"]},
{id:15,section:"B",category:"木構造",importance:"S",question:"二分探索木に 8, 3, 10, 1, 6 の順に値を挿入した。このとき値6の親ノードはどれか。",options:["1","3","8","10"]},
{id:16,section:"B",category:"探索",importance:"S",question:"昇順配列 [2, 6, 11, 18, 25, 31, 40, 47, 53] に二分探索で47を探す。最初に比較する値を中央要素とすると、比較値の順序として適切なものはどれか。",options:["25 → 40 → 47","25 → 47","31 → 47","25 → 31 → 40 → 47"]},
{id:17,section:"B",category:"アルゴリズム",importance:"S",question:"次の処理を実行したとき、sumの値はいくつか。",code:"sum ← 0\nfor i ← 1 to 4\n    for j ← 1 to i\n        sum ← sum + 1\n    endfor\nendfor",options:["4","6","10","16"]},
{id:18,section:"B",category:"配列",importance:"S",question:"次の処理を実行した後の配列Aはどれか。添字は1から始まる。",code:"A ← [1, 2, 3, 4, 5]\nfor i ← 1 to 2\n    t ← A[i]\n    A[i] ← A[6-i]\n    A[6-i] ← t\nendfor",options:["[5,4,3,2,1]","[5,2,3,4,1]","[4,5,3,1,2]","[2,1,3,5,4]"]},
{id:19,section:"B",category:"論理演算",importance:"S",question:"A=true、B=false のとき、(A AND NOT B) OR (NOT A AND B) の値はどれか。",options:["true","false","0","判定不能"]},
{id:20,section:"B",category:"疑似言語",importance:"S",question:"次の処理を実行したとき、xの値はいくつか。",code:"x ← 0\nfor i ← 1 to 5\n    if i MOD 2 = 0 then\n        x ← x + i * 2\n    else\n        x ← x + 1\n    endif\nendfor",options:["9","13","15","17"]}
];
